# ============================================
# Configuration Production - Simul'Enfance - RENDER
# ============================================

# PostgreSQL (depuis variables d'environnement Render)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration (depuis variables d'environnement)
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

# Server
server.port=${PORT:8080}

# Logging
logging.level.root=INFO
logging.level.com.municipal=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Sécurité
server.error.include-message=never
server.error.include-stacktrace=never